#!/usr/bin/env php
<?php
include('commands.php');

$opts = getopt ('d:u:p:h:' , [
    'file:',
    'create_table',
    'dry_run::',
    'help::',
    'verbose::'
] );


try{
    if(isset($opts['help'])){
        $command = new PrintHelpCommand($opts);
    } elseif (isset($opts['create_table'])){
        $command = new CreateTableCommand($opts);
    } else {
        $command = new ExportCommand($opts);
    }
    $command->execute();
}
catch(DBException $e){
    print 'DB Exception';
    die($e->getMessage());
}
catch(ParamException $e){
    print $e->getMessage();
    print "\n\r\n";
    $command = new PrintHelpCommand($opts);
    $command->execute();
}